export const COMPANY = {
  name: "NVS CHIT ENTERPRISES",
  address: "1538, North Veli Street, Simmakkal, Madurai – 625001",
  phone: "96009 4752",
  email: "nvschit@gmail.com",
  gstin: "33AABCS1234A1ZQ",
  cin: "U65923TN2001PTC048000",
  logo: "NVS",
  website: "nvschit.com",
  bankName: "State Bank of India",
  accountName: "NVS CHIT ENTERPRISES",
  accountNumber: "1234567890",
  ifscCode: "SBIN0001234",
  branch: "Madurai Main Branch",
  upiId: "nvschit@upi",
  googlePay: "nvschit@okhdfcbank",
  phonePe: "nvschit@ybl",
  paytm: "nvschit@paytm",
  bhim: "nvschit@upi",
  cardGateway: "Razorpay",
  merchantId: "rzp_test_12345678",
  apiKey: "rzp_test_abcdef123456",
  cashInstructions: "Please visit our office at 1538, North Veli Street, Simmakkal, Madurai – 625001. Contact: 96009 4752. Office hours: 9 AM - 6 PM, Monday - Saturday."
};

export const ROUTES = {
  dashboard: "/dashboard",
  members: "/members",
  schemes: "/schemes",
  groups: "/groups",
  collections: "/collections",
  billing: "/billing",
  auctions: "/auctions",
  prizes: "/prizes",
  accounting: "/accounting",
  reports: "/reports",
  employees: "/employees",
  branches: "/branches",
  notifications: "/notifications",
  settings: "/settings",
  profile: "/profile",
  payments: "/payments",
  addMembers: "/add-members",
  agents: "/agents",
  commissions: "/commissions",
  userManagement: "/user-management",
  enquiries: "/enquiries",
  auditLogs: "/audit-logs",
  kyc: "/kyc-verification",
};

export const ROUTE_TO_ID = Object.fromEntries(
  Object.entries(ROUTES).map(([id, path]) => [path, id])
);

export const NAV_ITEMS = [
  { id: "dashboard", label: "Dashboard", icon: "dashboard" },
  { id: "members", label: "Members", icon: "members" },
  { id: "schemes", label: "Chit Schemes", icon: "schemes" },
  { id: "groups", label: "Groups", icon: "groups" },
  { id: "collections", label: "Collections", icon: "collections" },
  { id: "billing", label: "Billing", icon: "billing" },
  { id: "auctions", label: "Auctions", icon: "auctions" },
  { id: "prizes", label: "Prize Payments", icon: "prizes" },
  { id: "accounting", label: "Accounting", icon: "accounting" },
  { id: "reports", label: "Reports", icon: "reports" },
  { id: "employees", label: "Employees", icon: "employees" },
  { id: "branches", label: "Branches", icon: "branches" },
  { id: "notifications", label: "Notifications", icon: "notifications" },
  { id: "settings", label: "Settings", icon: "settings" },
  { id: "profile", label: "My Profile", icon: "profile" },
  { id: "payments", label: "My Payments", icon: "payments" },
  { id: "enquiries", label: "Enquiries", icon: "enquiries" },
  { id: "agents", label: "Agents", icon: "members" },
  { id: "commissions", label: "Commissions", icon: "prizes" },
  { id: "user-management", label: "User Management", icon: "members" },
  { id: "audit-logs", label: "Audit Logs", icon: "reports" },
  { id: "kyc", label: "KYC Verification", icon: "profile" },
];
