export const COMPANY = {
  name: "NVS CHIT ENTERPRISES",
  address: "1538, North Veli Street, Simmakkal, Madurai – 625001",
  phone: "96009 4752",
  email: "nvschit@gmail.com",
  gstin: "33AABCS1234A1ZQ",
  cin: "U65923TN2001PTC048000",
  logo: "NVS",
  website: "nvschit.com",
  bankName: "State Bank of India",
  accountName: "NVS CHIT ENTERPRISES",
  accountNumber: "1234567890",
  ifscCode: "SBIN0001234",
  branch: "Madurai Main Branch",
  upiId: "nvschit@upi",
  googlePay: "nvschit@okhdfcbank",
  phonePe: "nvschit@ybl",
  paytm: "nvschit@paytm",
  bhim: "nvschit@upi",
  cardGateway: "Razorpay",
  merchantId: "rzp_test_12345678",
  apiKey: "rzp_test_abcdef123456",
  cashInstructions: "Please visit our office at 1538, North Veli Street, Simmakkal, Madurai – 625001. Contact: 96009 4752. Office hours: 9 AM - 6 PM, Monday - Saturday."
};

export const ROUTES = {
  dashboard: "/dashboard",
  members: "/members",
  schemes: "/schemes",
  groups: "/groups",
  collections: "/collections",
  billing: "/billing",
  auctions: "/auctions",
  prizes: "/prizes",
  accounting: "/accounting",
  reports: "/reports",
  employees: "/employees",
  branches: "/branches",
  notifications: "/notifications",
  settings: "/settings",
  profile: "/profile",
  payments: "/payments",
  invoices: "/invoices",
  receipts: "/receipts",
  support: "/support",
  addMembers: "/add-members",
  agents: "/agents",
  commissions: "/commissions",
  "user-management": "/user-management",
  enquiries: "/enquiries",
  "audit-logs": "/audit-logs",
  kyc: "/kyc-verification",
  "platform-settings": "/platform-settings",
  "invoice-settings": "/invoice-settings",
  "receipt-settings": "/receipt-settings",
  "notification-settings": "/notification-settings",
  "role-permissions": "/role-permissions",
  "backup-restore": "/backup-restore",
};

export const ROUTE_TO_ID = Object.fromEntries(
  Object.entries(ROUTES).map(([id, path]) => [path, id])
);

export const NAV_ITEMS = [
  { id: "dashboard", label: "Dashboard", icon: "dashboard" },
  { id: "branches", label: "Branches", icon: "branches" },
  { id: "schemes", label: "Chit Schemes", icon: "schemes" },
  { id: "groups", label: "Groups", icon: "groups" },
  { id: "agents", label: "Agent Management", icon: "agents" },
  { id: "members", label: "Members / Customers", icon: "members" },
  { id: "collections", label: "Collections", icon: "collections" },
  { id: "billing", label: "Billing", icon: "billing" },
  { id: "auctions", label: "Auctions", icon: "auctions" },
  { id: "prizes", label: "Prize Payment", icon: "prizes" },
  { id: "accounting", label: "Accounting", icon: "accounting" },
  { id: "reports", label: "Reports", icon: "reports" },
  { id: "enquiries", label: "Enquiries", icon: "enquiries" },
  { id: "notifications", label: "Notifications", icon: "notifications" },
  { id: "kyc", label: "KYC Verification", icon: "kyc" },
  { id: "user-management", label: "User Management", icon: "user-management" },
  { id: "audit-logs", label: "Audit Logs", icon: "audit-logs" },
  {
    id: "settings",
    label: "Settings",
    icon: "settings",
    children: [
      { id: "platform-settings", label: "Company Settings", icon: "platform-settings" },
      { id: "invoice-settings", label: "Invoice Settings", icon: "invoice-settings" },
      { id: "receipt-settings", label: "Receipt Settings", icon: "receipt-settings" },
      { id: "notification-settings", label: "Notification Settings", icon: "notification-settings" },
      { id: "role-permissions", label: "Role & Permissions", icon: "role-permissions" },
      { id: "backup-restore", label: "Backup & Restore", icon: "backup-restore" },
    ],
  },
];
